# Generated by Django 6.0.6 on 2026-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='empresa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='presupuesto',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='servicio',
            field=models.CharField(blank=True, choices=[('pagina_web', 'Página web'), ('sistema_web', 'Sistema web'), ('api', 'API / Integración'), ('automatizacion', 'Automatización'), ('agente_ia', 'Agente de IA'), ('otro', 'Otro / No estoy seguro')], max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
